### ISSUE TITLE
框架限制抓取出错

### ISSUE THREAD

**Issue by 280347211** [iothua/MFrameworkCore#24]
**描述错误**
Features模块中激活限制移动，Y轴限制，只对右手限制有用，对左手没用

![image](https://user-images.githubusercontent.com/33950901/49053101-a758dd80-f229-11e8-90a6-bc4e8e11b4e4.png)
`                    GameObject temp = KinectTransfer.GetObjectGrab(0); //只是右手
                    GameObject temp1 = KinectTransfer.GetObjectGrab(1);//添加左手
                   
                    if (temp!=null&&temp==grabObject)
                        OnUpdate();

                    if (temp1 != null && temp1 == grabObject)
                        OnUpdate();`

**Comment by iothua** [comment]
**信息接收成功**
* 反馈给刘为，收到请回复。 @LiiiiiWr
