### ISSUE TITLE
KGUI添加涂鸦功能

### ISSUE THREAD

**Issue by iothua** [iothua/MFrameworkCore#34]
**在KGUI新增涂鸦控件**
用于涂鸦
**在KGUI新增截屏控件**
触发某个按钮，对当前屏幕进行截屏，然后可进行图片的放大缩小、以及移动（当图片放大时，可移动里面的图片）。
* 缩放功能。
可了解新EventCameraZoom事件，可利用这事件完成缩放。
**两个控件都必须支持本地保存**
@PleaseDownloadLater

**Comment by iothua** [comment]
利用闲于时间。抽个时间完成。

**Comment by PleaseDownloadLater** [comment]
好的
